# Generated by Django 3.1.6 on 2021-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
